### ISSUE TITLE
getPageTerms: Fails with custom MODX table prefix

### ISSUE THREAD

**Issue by PeteVox** [craftsmancoding/taxonomies#16]
The 'getPageTerms' snippet contains SQL statement with table name  'modx_site_content' hard-coded. This breaks if using custom table prefixes for the MODX instance. 

Fixed by replacing with:

$content_table = $modx->getTableName('modResource');
$sql = "SELECT terms.term_id,doc.pagetitle
		FROM tax_page_terms terms
		LEFT JOIN $content_table doc ON doc.id = terms.term_id
		WHERE terms.page_id = {$page_id} {$and_where} ORDER BY doc.pagetitle ASC {$limit};";

Hope this helps. Great work on Taxonomies :)

**Comment by fireproofsocks** [comment]
Missed one.  Thanks for the report.

**Comment by PeteVox** [comment]
No problem Everett.

Have also just reworked the plugin logic slightly to enable skipping 
output of Taxonomies tab if the classkey OR template ID match system 
settings. I’m working on a site where I can’t just use classkey as ‘tab 
blocker’ (has to be done with Template Ids). Current plugin code was 
outputting the tab even when system settings (taxonomies.skip_templates) 
set with template Ids to ignore. 

The code below just tested in my local instance and works.

Again – great work on the component. 

Much appreciated.
 
Pete


<?php
/**
 * @name Taxonomies
 * @description 
 * @PluginEvents OnManagerPageInit,OnDocFormPrerender,OnDocFormSave
 * 
 */
 
$core_path = $modx->getOption('taxonomies.core_path', null, 
MODX_CORE_PATH.'components/taxonomies/');
include_once $core_path .'vendor/autoload.php';
$cache_dir = 'taxonomies';

switch ($modx->event->name) {

    
//-------------------------------------------------------------------------
-----
    //! OnManagerPageInit
    //  Load up custom CSS for the manager
    
//-------------------------------------------------------------------------
-----
    case 'OnManagerPageInit':
        $assets_url = $modx->getOption('taxonomies.assets_url', null, 
MODX_ASSETS_URL.'components/taxonomies/');
        $modx->log(modX::LOG_LEVEL_DEBUG,'Registering 
'.$assets_url.'css/taxonomies.css','','taxonomies 
Plugin:OnManagerPageInit');
        $modx->regClientCSS($assets_url.'css/taxonomies.tree.css');
        break;
    
//-------------------------------------------------------------------------
-----
    //! OnDocFormPrerender
    // Add a custom tab to the resource panel for resource types OTHER 
THAN Taxonomy
    // and Terms (no sense in categorizing categories). 
    // We have to use $_GET to read the class_key because it's otherwise 
not avail.
    // Remember: $resource will be null for new Resources!
    
//-------------------------------------------------------------------------
-----
    case 'OnDocFormPrerender':
        $modx->log(modX::LOG_LEVEL_DEBUG,'Getting Test','taxonomies 
Plugin:OnDocFormPrerender');
        $modx->lexicon->load('taxonomies:default’);
// $skip_classes build moved below
        if (empty($resource)) {
            $class_key = (isset($_GET['class_key'])) ? $_GET['class_key'] 
: 'modDocument';
            $template = (isset($_GET['template'])) ? $_GET['template'] : 
$modx->getOption('default_template');
        } else {
            $class_key = $resource->get('class_key');
            $template = $resource->get('template');
        }
        
        if($class_key=='Term')
        {
            $T = new \Taxonomies\Base($modx);
            $pages = $T->getTermList($id);
            $modx->regClientStartupHTMLBlock('<script 
type="text/javascript">
                MODx.on("ready",function() {
                    MODx.addTab("modx-resource-tabs",{
                        title: "'.$modx->lexicon('pages').'",
                        id: "pages-resource-tab",
                        width: "95%",
                        html: '.json_encode(utf8_encode("$pages")).'
                    });
                });
            </script>');
        } else {
            $skip_classes = array_merge(
                array('Taxonomy','Term'),
                array_map('trim', explode(',', 
$modx->getOption('taxonomies.skip_class_keys')))
            );
            $skip_templates = array_map('trim', explode(',', 
$modx->getOption('taxonomies.skip_templates')));
            if (!in_array($class_key,$skip_classes) && 
!in_array($template,$skip_templates)) {
                $T = new \Taxonomies\Base($modx);
                $form = $T->getForm($id);
                $modx->regClientStartupHTMLBlock('<script 
type="text/javascript">
                    MODx.on("ready",function() {
                        MODx.addTab("modx-resource-tabs",{
                            title: "'.$modx->lexicon('taxonomies').'",
                            id: "taxonomies-resource-tab",
                            width: "95%",
                            html: '.json_encode(utf8_encode("$form")).'
                        });
                    });                
                </script>');
            }
        }
        break;
        
    case 'OnDocFormSave':
        $modx->log(modX::LOG_LEVEL_DEBUG,'','','taxonomies 
Plugin:OnDocFormSave');
        if ($terms = $resource->get('terms')) {
            $T = new \Taxonomies\Base($modx);
            $T->dictatePageTerms($resource->get('id'), $terms);
        }
        break;
}

?>


From:  Everett Griffiths
Reply-To:  craftsmancoding/taxonomies
Date:  Wednesday, 18 February 2015 15:27
To:  craftsmancoding/taxonomies
Cc:  Pete Vox
Subject:  Re: [taxonomies] getPageTerms: Fails with custom MODX table 
prefix (#16)


Missed one.  Thanks for the report.

**Comment by fireproofsocks** [comment]
Fixed in 1.3.1.

edec0c7..fc6a1e6  master -> master
