### ISSUE TITLE
URL link in innerTpl of getPageTerms not showing

### ISSUE THREAD

**Issue by thachayoot** [craftsmancoding/taxonomies#20]
I've tried this

[[~[[+term_id]] ]]  and  [[~[[+id]] ]]
but neither of them seem to work.

**Comment by fireproofsocks** [comment]
What's the full Snippet call you're using?  And which version of Taxonomies are you using?

**Comment by thachayoot** [comment]
Hi

I use version 1.3.0-pl with modx 2.3.2-pl and the snippet call are as
following;

According to your code on Github

[[getPageTerms? &outerTpl=`` &innerTpl=`<a class="b-tag"
> href="[[~[[+term_id]]]]">[[+pagetitle]]</a>`]]


and this one according to your wiki
<https://github.com/craftsmancoding/taxonomies/wiki/getTagCloud>

[[getPageTerms? &outerTpl=`` &innerTpl=`<a class="b-tag"
> href="[[~[[+id]]]]">[[+pagetitle]]</a>`]]
>

 Regards,

Joe

On 18 March 2015 at 03:02, Everett Griffiths <notifications@github.com>
wrote:

> What's the full Snippet call you're using? And which version of Taxonomies
> are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/craftsmancoding/taxonomies/issues/20#issuecomment-82435414>
> .
>



-- 
[image: me] *Joe Sangkhamanee*
*Web Developer*
*Fab Web Design : Sydney Web Design & SEO Services
<http://www.fabwebdesign.com.au>*
2/34 Pomeroy St, Homebush NSW 2140
*Tel. 0432 445 177*
| email: info@fabwebdesign.com.au | <info@fabwebdesign.com.au>

**Comment by fireproofsocks** [comment]
Try re-doing these so you use a real Chunk instead of the formatting strings: the formatting strings have issues with parsing because the placeholders get replaced before they make it to the snippet.  Sorry if the wiki example is out of date.

**Comment by thachayoot** [comment]
Thanks for your reply. It works well with the real Chunk. Appreciate your
work and support.

Regards,

Joe

On 18 March 2015 at 10:04, Everett Griffiths <notifications@github.com>
wrote:

> Try re-doing these so you use a real Chunk instead of the formatting
> strings: the formatting strings have issues with parsing because the
> placeholders get replaced before they make it to the snippet. Sorry if the
> wiki example is out of date.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/craftsmancoding/taxonomies/issues/20#issuecomment-82634310>
> .
>



-- 
[image: me] *Joe Sangkhamanee*
*Web Developer*
*Fab Web Design : Sydney Web Design & SEO Services
<http://www.fabwebdesign.com.au>*
2/34 Pomeroy St, Homebush NSW 2140
*Tel. 0432 445 177*
| email: info@fabwebdesign.com.au | <info@fabwebdesign.com.au>

**Comment by fireproofsocks** [comment]
I updated the example in the docs.
