### ISSUE TITLE
Remove .gitignore from transport package / build

### ISSUE THREAD

**Issue by markwillis82** [craftsmancoding/taxonomies#24]
Having the .gitignore inside `core/components/taxonomies` causes headaches with the `vendor/` folder for projects that are using source control.

Because the `vendor/` folder is ignored from git once the package is committed it fails to work on other machines because this folder no longer exists.

The only way to get around this is to run a `git add --force` which is not ideal.

**Comment by fireproofsocks** [comment]
Yep: the whole package management here is not ideal -- the proper way to handle this is to use composer as MODX's package manager and rely on a master (i.e. root) composer.json file.  The plan here is to publish the modx-package spec (https://github.com/craftsmancoding/repoman/wiki/Spec) and release Repoman as a composer plugin to handle them (see https://github.com/craftsmancoding/repoman/issues/15).

So until those things are resolved, we are stuck in "not ideal" territory.  It's not ideal to use `git add --force` and it's not ideal to omit `vendor/` from the .gitignore file.

**Comment by markwillis82** [comment]
The .gitignore file doesn't need to be updated, it would just need to be excluded from the transport.zip file that is created and published through modx.com extras.

If/When the time comes that MODX is has extras installed via composer then this wouldn't be a problem anyway (as the transport.zip wouldn't be used).

**Comment by fireproofsocks** [comment]
Ah, I see your point.  Yes, for the next build, I'll add .gitignore to Repoman's "omit" argument.  Thanks for pointing this out.

**Comment by fireproofsocks** [comment]
Releasing version 1.3.2 today: this omits the .gitignore from the package and implements a couple minor improvements.
